@startuml
start

:Step 4 - Get First Deco Stop Depth;
:Set currentStop = FirstStop;
:Set LastStop = 3msw  // or the desired last stop depth

repeat
  :Get DecoGas for current stop;
  :Set StopLength = 0;
  
  repeat
    :CalculateAtDepth|
    :Depth = currentStop;
    :Bottom Time = 1 min;
    :GasMix = DecoGas;
    :Increment StopLength by 1;
  repeat while (AscentCeiling != (currentStop - 3msw))
  
  :Total stop time = StopLength minutes;
  :Move up to next stop depth (currentStop = currentStop - 3msw);


stop
@enduml
